### ISSUE TITLE
Install LaTeX

### ISSUE THREAD

**Issue by geets04** [RechercheTech/mss#54]
LaTeX to be installed, as available in syllabus .

**Comment by cyberorg** [comment]
For earlier mss releases Latex is purposely not included due to it's huge size, use online latex editors [online latex editor](https://www.google.com/search?q=best+online+latex+editor )for the demonstration in classes.

New MSS installs with the above commit will have latex support in scite as described in textbook.

**Comment by geets04** [comment]
Testing done of LaTeX , working fine with scite .
